/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/model/FordMustangGT_2023.gltf 
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { motion, useAnimation } from "framer-motion";

function FordMustangGT_2023(props) {
  const [isDoorOpen, setIsDoorOpen] = useState(false);
  const [isDoorClose, setIsDoorClose] = useState(false);
  const { nodes, materials } = useGLTF("./model/FordMustangGT_2023.gltf");
  const controls = useAnimation();

  const handleToggleDoor = () => {
    setIsDoorOpen(!isDoorOpen);
    setIsDoorClose(!isDoorClose);
    controls.start({
      rotation: isDoorOpen ? [0, -1, 0] : isDoorClose ? [0, 0, 0] : [0, 0, 0],
    });
  };

  // Define rotation values for open and closed states
  const L_closedRotation = [0, 0, 0];
  const L_openRotation = [0, -1, 0];

  const R_closedRotation = [0, 0, 0];
  const R_openRotation = [0, 1, 0];

  return (
    <group {...props} dispose={null}>
      <group
        position={[0.596, 0.69, -0.852]}
        rotation={isDoorOpen ? L_openRotation : L_closedRotation}
        onClick={handleToggleDoor}
      >
        {/* <Html>
          <button onClick={handleToggleDoor}>Door Open</button>
        </Html> */}
        <group position={[-0.54, 0.08, 0.081]}>
          <mesh
            geometry={nodes.tex_Left_Door.geometry}
            material={materials.carpaint}
          />
          <mesh
            geometry={nodes.tex_Left_Door_1.geometry}
            material={materials.chrome}
          />
          <mesh
            geometry={nodes.tex_Left_Door_2.geometry}
            material={materials.glass_dark}
          />
          <mesh
            geometry={nodes.tex_Left_Door_3.geometry}
            material={materials.leatherA}
          />
          <mesh
            geometry={nodes.tex_Left_Door_4.geometry}
            material={materials.leatherB}
          />
          <mesh
            geometry={nodes.tex_Left_Door_5.geometry}
            material={materials.plasticblack}
          />
          <mesh
            geometry={nodes.tex_Left_Door_6.geometry}
            material={materials.plasticGlossy}
          />
          <mesh
            geometry={nodes.tex_Left_Door_7.geometry}
            material={materials.plasticInt}
          />
          <mesh
            geometry={nodes.tex_Left_Door_8.geometry}
            material={materials.plasticIntPattern}
          />
          <mesh
            geometry={nodes.tex_Left_Door_9.geometry}
            material={materials.plasticMatt}
          />
          <mesh
            geometry={nodes.tex_Left_Door_10.geometry}
            material={materials.reflect}
          />
          <mesh
            geometry={nodes.tex_Left_Door_11.geometry}
            material={materials.seam}
          />
          <mesh
            geometry={nodes.tex_Left_Door_12.geometry}
            material={materials["seamB.001"]}
          />
          <mesh
            geometry={nodes.tex_Left_Door_13.geometry}
            material={materials.silver}
          />
          <mesh
            geometry={nodes.tex_Left_Door_14.geometry}
            material={materials.int}
          />
        </group>
      </group>
      <group
        position={[0.596, 0.69, 0.9]}
        rotation={isDoorClose ? R_openRotation : R_closedRotation}
      >
        <group position={[-0.534, 0.082, -0.08]}>
          <mesh
            geometry={nodes.tex_Right_Door.geometry}
            material={materials.int}
          />
          <mesh
            geometry={nodes.tex_Right_Door_1.geometry}
            material={materials.carpaint}
          />
          <mesh
            geometry={nodes.tex_Right_Door_2.geometry}
            material={materials.glass_dark}
          />
          <mesh
            geometry={nodes.tex_Right_Door_3.geometry}
            material={materials.leatherA}
          />
          <mesh
            geometry={nodes.tex_Right_Door_4.geometry}
            material={materials.leatherB}
          />
          <mesh
            geometry={nodes.tex_Right_Door_5.geometry}
            material={materials.plasticblack}
          />
          <mesh
            geometry={nodes.tex_Right_Door_6.geometry}
            material={materials.plasticGlossy}
          />
          <mesh
            geometry={nodes.tex_Right_Door_7.geometry}
            material={materials.plasticInt}
          />
          <mesh
            geometry={nodes.tex_Right_Door_8.geometry}
            material={materials.plasticIntPattern}
          />
          <mesh
            geometry={nodes.tex_Right_Door_9.geometry}
            material={materials.plasticMatt}
          />
          <mesh
            geometry={nodes.tex_Right_Door_10.geometry}
            material={materials.reflect}
          />
          <mesh
            geometry={nodes.tex_Right_Door_11.geometry}
            material={materials.seam}
          />
          <mesh
            geometry={nodes.tex_Right_Door_12.geometry}
            material={materials["seamB.001"]}
          />
          <mesh
            geometry={nodes.tex_Right_Door_13.geometry}
            material={materials.silver}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Body.geometry}
        material={materials.carpaint}
        position={[-2.143, 0.557, 0.024]}
      />
      <mesh
        geometry={nodes.brakeCaliper_000_LR_wheels.geometry}
        material={materials.brakeCaliper}
        position={[1.167, 0.344, -0.75]}
      />
      <mesh
        geometry={nodes.brakeCaliper_001_LR_wheels.geometry}
        material={materials.brakeCaliper}
        position={[-1.234, 0.374, -0.822]}
      />
      <mesh
        geometry={nodes.brakeCaliper_002_LR_wheels.geometry}
        material={materials.brakeCaliper}
        position={[1.167, 0.344, 0.798]}
      />
      <mesh
        geometry={nodes.brakeCaliper_003_LR_wheels.geometry}
        material={materials.brakeCaliper}
        position={[-1.234, 0.374, 0.87]}
      />
      <mesh
        geometry={nodes.brakeDisc_000_LR_wheels.geometry}
        material={materials.chrome_brushed_brakedisc}
        position={[1.336, 0.349, -0.75]}
      />
      <mesh
        geometry={nodes.brakeDisc_001_LR_wheels.geometry}
        material={materials.chrome_brushed_brakedisc}
        position={[-1.384, 0.354, -0.765]}
      />
      <mesh
        geometry={nodes.brakeDisc_002_LR_wheels.geometry}
        material={materials.chrome_brushed_brakedisc}
        position={[1.336, 0.349, 0.798]}
      />
      <mesh
        geometry={nodes.brakeDisc_003_LR_wheels.geometry}
        material={materials.chrome_brushed_brakedisc}
        position={[-1.384, 0.354, 0.813]}
      />
      <mesh
        geometry={nodes.metal_brakeDisk00_LR_wheels.geometry}
        material={materials.metal_def}
        position={[1.336, 0.349, -0.777]}
      />
      <mesh
        geometry={nodes.metal_brakeDisk001_LR_wheels.geometry}
        material={materials.metal_def}
        position={[-1.384, 0.354, -0.795]}
      />
      <mesh
        geometry={nodes.metal_brakeDisk002_LR_wheels.geometry}
        material={materials.metal_def}
        position={[1.336, 0.349, 0.825]}
      />
      <mesh
        geometry={nodes.metal_brakeDisk003_LR_wheels.geometry}
        material={materials.metal_def}
        position={[-1.384, 0.354, 0.844]}
      />
      <mesh
        geometry={nodes.metalBright_brakeCaliper_000_LR_wheels.geometry}
        material={materials.black}
        position={[1.139, 0.388, -0.75]}
      />
      <mesh
        geometry={nodes.metalBright_brakeCaliper_001_LR_wheels.geometry}
        material={materials.black}
        position={[-1.232, 0.434, -0.822]}
      />
      <mesh
        geometry={nodes.metalBright_brakeCaliper_002_LR_wheels.geometry}
        material={materials.black}
        position={[1.139, 0.388, 0.798]}
      />
      <mesh
        geometry={nodes.metalBright_brakeCaliper_003_LR_wheels.geometry}
        material={materials.black}
        position={[-1.232, 0.434, 0.87]}
      />
      <mesh
        geometry={nodes.plasticBlack_brakeCaliper_000_LR_wheels.geometry}
        material={materials.plasticblack}
        position={[1.184, 0.488, -0.75]}
      />
      <mesh
        geometry={nodes.plasticBlack_brakeCaliper_001_LR_wheels.geometry}
        material={materials.plasticblack}
        position={[-1.253, 0.489, -0.822]}
      />
      <mesh
        geometry={nodes.plasticBlack_brakeCaliper_002_LR_wheels.geometry}
        material={materials.plasticblack}
        position={[1.184, 0.488, 0.798]}
      />
      <mesh
        geometry={nodes.plasticBlack_brakeCaliper_003_LR_wheels.geometry}
        material={materials.plasticblack}
        position={[-1.253, 0.489, 0.87]}
      />
      <group position={[1.336, 0.569, -0.859]}>
        <mesh
          geometry={nodes.plasticBlack_valve000_LR_wheels.geometry}
          material={materials.plasticblack}
        />
        <mesh
          geometry={nodes.plasticBlack_valve000_LR_wheels_1.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes.plasticBlack_valve000_LR_wheels_2.geometry}
          material={materials.rimDark}
        />
      </group>
      <group position={[-1.384, 0.574, -0.886]}>
        <mesh
          geometry={nodes.plasticBlack_valve001_LR_wheels.geometry}
          material={materials.plasticblack}
        />
        <mesh
          geometry={nodes.plasticBlack_valve001_LR_wheels_1.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes.plasticBlack_valve001_LR_wheels_2.geometry}
          material={materials.rimDark}
        />
      </group>
      <group position={[1.336, 0.569, 0.907]}>
        <mesh
          geometry={nodes.plasticBlack_valve002_LR_wheels.geometry}
          material={materials.plasticblack}
        />
        <mesh
          geometry={nodes.plasticBlack_valve002_LR_wheels_1.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes.plasticBlack_valve002_LR_wheels_2.geometry}
          material={materials.rimDark}
        />
      </group>
      <group position={[-1.384, 0.574, 0.934]}>
        <mesh
          geometry={nodes.plasticBlack_valve003_LR_wheels.geometry}
          material={materials.plasticblack}
        />
        <mesh
          geometry={nodes.plasticBlack_valve003_LR_wheels_1.geometry}
          material={materials.chrome}
        />
        <mesh
          geometry={nodes.plasticBlack_valve003_LR_wheels_2.geometry}
          material={materials.rimDark}
        />
      </group>
      <mesh
        geometry={nodes["02_Left_front_wheels_Tire"].geometry}
        material={materials.tire}
        position={[1.336, 0.349, -0.746]}
      />
      <mesh
        geometry={nodes["03_Left_rear_wheels_Tire"].geometry}
        material={materials.tire}
        position={[-1.384, 0.354, -0.761]}
      />
      <mesh
        geometry={nodes["04_Right_rear_wheels_Tire"].geometry}
        material={materials.tire}
        position={[-1.384, 0.354, 0.809]}
      />
      <mesh
        geometry={nodes["01_Right_front_wheels_Tire"].geometry}
        material={materials.tire}
        position={[1.336, 0.349, 0.794]}
      />
      <mesh
        geometry={nodes.black_int_LR_interior.geometry}
        material={materials.black}
        position={[0.392, 0.916, 0.104]}
      />
      <mesh
        geometry={nodes.carpet_bottom_LR_interior.geometry}
        material={materials.carpet}
        position={[-0.005, 0.313, 0.028]}
      />
      <mesh
        geometry={nodes.chrome_stickShift_LR_interior.geometry}
        material={materials.chrome}
        position={[0.098, 0.67, 0.024]}
      />
      <mesh
        geometry={nodes.leatherA_centConsole_LR_interior.geometry}
        material={materials.leatherA}
        position={[0.03, 0.477, 0.03]}
      />
      <mesh
        geometry={nodes.leatherA_dash_LR_interior.geometry}
        material={materials.leatherA}
        position={[0.331, 0.827, -0.062]}
      />
      <mesh
        geometry={nodes.leatherA_handrbake_LR_interior.geometry}
        material={materials.leatherA}
        position={[0.003, 0.563, -0.08]}
      />
      <mesh
        geometry={nodes.leatherA_intRear_LR_interior.geometry}
        material={materials.leatherA}
        position={[-0.885, 0.784, 0.024]}
      />
      <mesh
        geometry={nodes.leatherA_seats_f_LR_interior.geometry}
        material={materials.leatherA}
        position={[-0.512, 0.659, 0.024]}
      />
      <mesh
        geometry={nodes.leatherA_seats_r_LR_interior.geometry}
        material={materials.leatherA}
        position={[-1.039, 0.699, 0.024]}
      />
      <mesh
        geometry={nodes.leatherA_stickShift_LR_interior.geometry}
        material={materials.leatherA}
        position={[0.092, 0.609, 0.024]}
      />
      <mesh
        geometry={nodes.leatherA_sw_LR_interior.geometry}
        material={materials.leatherA}
        position={[0.137, 0.87, -0.315]}
      />
      <mesh
        geometry={nodes.leatherB_seats_f_LR_interior.geometry}
        material={materials.leatherB}
        position={[-0.34, 0.567, 0.024]}
      />
      <mesh
        geometry={nodes.leatherB_seats_r_LR_interior.geometry}
        material={materials.leatherB}
        position={[-1.005, 0.689, 0.024]}
      />
      <mesh
        geometry={nodes.leatherPerforated_sw_LR_interior.geometry}
        material={materials.leatherA_perforated}
        position={[0.131, 0.865, -0.315]}
      />
      <mesh
        geometry={
          nodes.perforated_seats_f_overlay_noShadow_LR_interior.geometry
        }
        material={materials.seatsPattern}
        position={[-0.359, 0.471, 0.024]}
      />
      <mesh
        geometry={
          nodes.perforated_seats_r_overlay_noShadow_LR_interior.geometry
        }
        material={materials.seatsPattern}
        position={[-1.017, 0.661, 0.024]}
      />
      <mesh
        geometry={nodes.plastic_buttons_sw_LR_interior.geometry}
        material={materials.plasticblack}
        position={[0.125, 0.865, -0.302]}
      />
      <mesh
        geometry={nodes.plastic_centConsole_LR_interior.geometry}
        material={materials.plasticblack}
        position={[-0.106, 0.532, 0.027]}
      />
      <mesh
        geometry={nodes.plastic_dash_left_panel_LR_interior.geometry}
        material={materials.plasticblack}
        position={[0.327, 0.758, -0.548]}
      />
      <mesh
        geometry={nodes.plastic_dash_LR_interior.geometry}
        material={materials.plasticblack}
        position={[0.332, 0.817, -0.093]}
      />
      <mesh
        geometry={nodes.plastic_dash_top_LR_interior.geometry}
        material={materials.plasticblack}
        position={[0.656, 0.981, 0.024]}
      />
      <mesh
        geometry={nodes.plastic_displays_LR_interior.geometry}
        material={materials.plasticblack}
        position={[0.344, 0.928, -0.115]}
      />
      <mesh
        geometry={nodes.plastic_handbrake_LR_interior.geometry}
        material={materials.plasticblack}
        position={[0.004, 0.563, -0.09]}
      />
      <mesh
        geometry={nodes.plastic_pedals_LR_interior.geometry}
        material={materials.plasticblack}
        position={[0.732, 0.415, -0.298]}
      />
      <mesh
        geometry={nodes.plastic_seatbelts001_LR_interior.geometry}
        material={materials.plasticblack}
        position={[-0.682, 0.821, 0.024]}
      />
      <mesh
        geometry={nodes.plastic_sw_airag_noMS_LR_interior.geometry}
        material={materials.plastic_matt_black}
        position={[0.075, 0.846, -0.314]}
      />
      <mesh
        geometry={nodes.plastic_sw_LR_interior.geometry}
        material={materials.plasticblack}
        position={[0.118, 0.816, -0.315]}
      />
      <mesh
        geometry={nodes.plasticBlack_pedals_LR_interior.geometry}
        material={materials.plasticblack}
        position={[0.759, 0.369, -0.172]}
      />
      <mesh
        geometry={nodes.plasticBumpB_logo_dash_LR_interior.geometry}
        material={materials.plasticblack_bumpB}
        position={[0.318, 0.924, 0.451]}
      />
      <mesh
        geometry={nodes.plasticD_badge_sw_LR_interior.geometry}
        material={materials.plasticblackD}
        position={[0.092, 0.877, -0.318]}
      />
      <mesh
        geometry={nodes.plasticGlossy_dash_decor_LR_interior.geometry}
        material={materials.plasticGlossy}
        position={[0.326, 0.923, 0.431]}
      />
      <mesh
        geometry={nodes.plasticGlossy_displays_LR_interior.geometry}
        material={materials.plasticGlossy}
        position={[0.322, 0.927, -0.114]}
      />
      <mesh
        geometry={nodes.plasticInt_centConsole001_LR_interior.geometry}
        material={materials.plasticInt}
        position={[0.265, 0.543, 0.031]}
      />
      <mesh
        geometry={nodes.plasticInt_centConsole002_LR_interior.geometry}
        material={materials.plasticInt}
        position={[-0.057, 0.513, 0.027]}
      />
      <mesh
        geometry={nodes.plasticInt_dash001_LR_interior.geometry}
        material={materials.plasticInt}
        position={[0.449, 0.728, -0.042]}
      />
      <mesh
        geometry={nodes.plasticInt_dash_LR_interior.geometry}
        material={materials.plasticInt}
        position={[0.266, 0.664, 0.026]}
      />
      <mesh
        geometry={nodes.plasticInt_dash_sides_LR_interior.geometry}
        material={materials.plasticInt}
        position={[0.452, 0.83, 0.028]}
      />
      <mesh
        geometry={nodes.plasticInt_interior_shell_LR_interior.geometry}
        material={materials.plasticInt}
        position={[-0.514, 0.781, 0.024]}
      />
      <mesh
        geometry={nodes.plasticInt_seats_f_LR_interior.geometry}
        material={materials.plasticInt}
        position={[-0.529, 0.813, 0.024]}
      />
      <mesh
        geometry={nodes.plasticInt_steeringColumn_LR_interior.geometry}
        material={materials.plasticInt}
        position={[0.259, 0.859, -0.315]}
      />
      <mesh
        geometry={nodes.plasticIntPattern_centConsole_LR_interior.geometry}
        material={materials.plasticIntPattern}
        position={[0.098, 0.548, 0.024]}
      />
      <mesh
        geometry={nodes.plasticIntPattern_dash_LR_interior.geometry}
        material={materials.plasticIntPattern}
        position={[0.344, 0.921, -0.04]}
      />
      <mesh
        geometry={
          nodes.plasticIntPattern_dash_vents_center_LR_interior.geometry
        }
        material={materials.plasticIntPattern}
        position={[0.277, 0.723, 0.026]}
      />
      <mesh
        geometry={nodes.plasticIntPattern_sw_LR_interior.geometry}
        material={materials.plasticIntPattern}
        position={[0.112, 0.822, -0.315]}
      />
      <mesh
        geometry={nodes.plasticMatt_doorWay_LR_interior.geometry}
        material={materials.plasticMatt}
        position={[0.037, 0.339, 0.024]}
      />
      <mesh
        geometry={nodes.seam_dash_noShadows_LR_interior.geometry}
        material={materials.seam}
        position={[0.314, 0.812, -0.042]}
      />
      <mesh
        geometry={nodes.seam_stickShift_noShadows_LR_interior.geometry}
        material={materials.seam}
        position={[0.061, 0.562, 0.023]}
      />
      <mesh
        geometry={nodes.seams_center_noShadows_LR_interior.geometry}
        material={materials.seam}
        position={[0.147, 0.506, 0.029]}
      />
      <mesh
        geometry={nodes.seams_seat_f_noShadows001_LR_interior.geometry}
        material={materials.seam}
        position={[-0.403, 0.639, 0.024]}
      />
      <mesh
        geometry={nodes.seamsB_seat_f_noShadows_LR_interior.geometry}
        material={materials.seamB}
        position={[-0.29, 0.585, 0.024]}
      />
      <mesh
        geometry={nodes.seatbelts_LR_interior.geometry}
        material={materials.seatbelt}
        position={[-0.913, 0.783, 0.024]}
      />
      <mesh
        geometry={nodes.silver_badge_sw_LR_interior.geometry}
        material={materials.silver}
        position={[0.092, 0.878, -0.32]}
      />
      <mesh
        geometry={nodes.silver_buttons_sw_LR_interior.geometry}
        material={materials.silver}
        position={[0.128, 0.863, -0.411]}
      />
      <mesh
        geometry={nodes.silver_centConsole_LR_interior.geometry}
        material={materials.silver}
        position={[-0.132, 0.568, 0.067]}
      />
      <mesh
        geometry={nodes.silver_handbrake_LR_interior.geometry}
        material={materials.silver}
        position={[-0.03, 0.556, -0.081]}
      />
      <mesh
        geometry={nodes.silver_logo_dash_LR_interior.geometry}
        material={materials.silver}
        position={[0.318, 0.924, 0.451]}
      />
      <mesh
        geometry={nodes.silver_pedals_LR_interior.geometry}
        material={materials.silver}
        position={[0.744, 0.412, -0.256]}
      />
      <mesh
        geometry={nodes.silver_stickShift_LR_interior.geometry}
        material={materials.silver}
        position={[0.095, 0.604, 0.024]}
      />
      <mesh
        geometry={nodes.silver_sw_LR_interior.geometry}
        material={materials.silver}
        position={[0.108, 0.822, -0.315]}
      />
      <mesh
        geometry={nodes.silverBumpB_dials001_LR_interior.geometry}
        material={materials.silverBumpB}
        position={[0.227, 0.684, 0.091]}
      />
      <mesh
        geometry={nodes.silverBumpB_dials_LR_interior.geometry}
        material={materials.silverBumpB}
        position={[0.325, 0.758, -0.56]}
      />
      <mesh
        geometry={nodes.texInt_buttons_sw_noShadows_LR_interior.geometry}
        material={materials.int}
        position={[0.125, 0.864, -0.315]}
      />
      <mesh
        geometry={nodes.texInt_dash_bottom_LR_interior.geometry}
        material={materials.int}
        position={[0.25, 0.696, 0.008]}
      />
      <mesh
        geometry={nodes.texInt_dash_left_panel_noShadows_LR_interior.geometry}
        material={materials.int}
        position={[0.332, 0.759, -0.531]}
      />
      <mesh
        geometry={nodes.texInt_logo_dash_noShadows_LR_interior.geometry}
        material={materials.int}
        position={[0.318, 0.924, 0.451]}
      />
      <mesh
        geometry={nodes.texInt_recaro_seats_f_noShadows_LR_interior.geometry}
        material={materials.int}
        position={[-0.618, 0.915, 0.024]}
      />
      <mesh
        geometry={nodes.texInt_speaker_dash_top_LR_interior.geometry}
        material={materials.int}
        position={[0.529, 0.989, 0.036]}
      />
      <mesh
        geometry={nodes.texInt_speakers_pillarA_LR_interior.geometry}
        material={materials.int}
        position={[0.338, 1.053, 0.024]}
      />
      <mesh
        geometry={nodes.texInt_steeringColumn_noShadows_LR_interior.geometry}
        material={materials.int}
        position={[0.21, 0.917, -0.315]}
      />
      <mesh
        geometry={nodes.texInt_usb_noShadows_LR_interior.geometry}
        material={materials.int}
        position={[0.329, 0.551, -0.022]}
      />
      <mesh
        geometry={nodes.texIntGlossy_displays_LR_interior.geometry}
        material={materials.intGlossy}
        position={[0.326, 0.929, -0.165]}
      />
      <mesh
        geometry={nodes.texIntSilver_doorSills_LR_interior.geometry}
        material={materials.intSilver}
        position={[0.04, 0.338, 0.024]}
      />
      <mesh
        geometry={nodes.texIntSlver_stickShift_LR_interior.geometry}
        material={materials.intSilverBump}
        position={[0.097, 0.671, 0.025]}
      />
      <mesh
        geometry={nodes.silver_dash_LR_interior.geometry}
        material={materials.silver}
        position={[0.283, 0.87, 0.045]}
      />
      <mesh
        geometry={nodes.interiorA_ceiling_LR_interior.geometry}
        material={materials.interiorA}
        position={[-0.414, 1.257, 0.024]}
      />
      <mesh
        geometry={nodes.interiorA_sunVisors_LR_interior.geometry}
        material={materials.interiorA}
        position={[0.003, 1.27, 0.024]}
      />
      <mesh
        geometry={nodes.plastic_intMirror_LR_interior.geometry}
        material={materials.plasticblack}
        position={[0.115, 1.228, 0.042]}
      />
      <mesh
        geometry={nodes.plasticInt_headliner_LR_interior.geometry}
        material={materials.plasticInt}
        position={[-0.141, 1.293, 0.024]}
      />
      <mesh
        geometry={nodes.reflect_mirrorInt_LR_interior.geometry}
        material={materials.reflect}
        position={[0.063, 1.214, 0.021]}
      />
      <mesh
        geometry={nodes.texInt_headliner_LR_interior.geometry}
        material={materials.int}
        position={[-0.023, 1.283, 0.024]}
      />
      <mesh
        geometry={nodes.black_exhaust_LR_exterior.geometry}
        material={materials.black}
        position={[-2.238, 0.31, 0.024]}
      />
      <mesh
        geometry={nodes.black_front_LR_exterior.geometry}
        material={materials.black}
        position={[1.972, 0.603, 0.024]}
      />
      <mesh
        geometry={nodes.black_rearWindow001_LR_exterior.geometry}
        material={materials.black}
        position={[-1.43, 1.164, 0.024]}
      />
      <mesh
        geometry={nodes.black_sideWindows001_LR_exterior.geometry}
        material={materials.black}
        position={[-0.98, 1.095, 0.024]}
      />
      <mesh
        geometry={nodes.chrome_doorClasp_LR_exterior.geometry}
        material={materials.chrome}
        position={[-0.671, 0.692, 0.024]}
      />
      <mesh
        geometry={nodes.glassDark_rearCam_LR_exterior.geometry}
        material={materials.glass_dark}
        position={[-2.38, 0.923, 0.024]}
      />
      <mesh
        geometry={nodes.glassDarkB_rearWindow_LR_exterior.geometry}
        material={materials.glass_darkB}
        position={[-1.413, 1.173, 0.024]}
      />
      <mesh
        geometry={nodes.glassDarkB_sideWindows_LR_exterior.geometry}
        material={materials.glass_darkB}
        position={[-0.98, 1.091, 0.024]}
      />
      <mesh
        geometry={nodes.glassLans_headlights_LR_exterior.geometry}
        material={materials.glass_lens}
        position={[1.915, 0.688, 0.024]}
      />
      <mesh
        geometry={nodes.glassMatt_headlightLED_LR_exterior.geometry}
        material={materials.glass_matt}
        position={[1.963, 0.721, 0.024]}
      />
      <mesh
        geometry={nodes.glassOrange_bumper_f_LR_exterior.geometry}
        material={materials.glass_orange}
        position={[1.749, 0.451, 0.024]}
      />
      <mesh
        geometry={nodes.glassRed_bumper_r001_LR_exterior.geometry}
        material={materials.glass_red}
        position={[-1.805, 0.462, 0.024]}
      />
      <mesh
        geometry={nodes.glassRed_bumper_r_LR_exterior.geometry}
        material={materials.glass_red}
        position={[-2.35, 0.415, 0.024]}
      />
      <mesh
        geometry={nodes.glassRedIllum_taillight_LR_exterior.geometry}
        material={materials.glass_red_illum}
        position={[-2.23, 0.849, 0.024]}
      />
      <mesh
        geometry={nodes.glassRedMatt_taillights_LR_exterior.geometry}
        material={materials.glass_red_matt}
        position={[-2.288, 0.847, 0.024]}
      />
      <mesh
        geometry={nodes.led_headlight_LR_exterior.geometry}
        material={materials.led}
        position={[1.963, 0.717, 0.024]}
      />
      <mesh
        geometry={nodes.metalDark_exhaust_LR_exterior.geometry}
        material={materials.metal_dark}
        position={[-2.27, 0.31, 0.024]}
      />
      <mesh
        geometry={nodes.metalDark_radiator_LR_exterior.geometry}
        material={materials.metal_dark}
        position={[1.998, 0.5, 0.024]}
      />
      <mesh
        geometry={nodes.metalDef_exhaust_LR_exterior.geometry}
        material={materials.metal_def}
        position={[-2.051, 0.297, 0.024]}
      />
      <mesh
        geometry={nodes.metalTinted_exhaust_LR_exterior.geometry}
        material={materials.metal_tinted}
        position={[-2.301, 0.308, 0.024]}
      />
      <mesh
        geometry={nodes.numberplate_r_LR_exterior.geometry}
        material={materials.plasticblack}
        position={[-2.427, 0.592, 0.024]}
      />
      <mesh
        geometry={nodes.orangeIllum_bumper_f_LR_exterior.geometry}
        material={materials.orange_illum}
        position={[1.76, 0.407, 0.024]}
      />
      <mesh
        geometry={nodes.plasticBlack_bumper_f_LR_exterior.geometry}
        material={materials.plasticblack}
        position={[2.072, 0.38, 0.024]}
      />
      <mesh
        geometry={nodes.plasticBlack_bumper_r_LR_exterior.geometry}
        material={materials.plasticblack}
        position={[-2.307, 0.378, 0.024]}
      />
      <mesh
        geometry={nodes.plasticBlack_bumper_r_noShadow_LR_exterior.geometry}
        material={materials.plasticblack}
        position={[-2.409, 0.468, 0.024]}
      />
      <mesh
        geometry={nodes.plasticBlack_doorHinge_LR_exterior.geometry}
        material={materials.plasticblack}
        position={[0.553, 0.646, 0.024]}
      />
      <mesh
        geometry={nodes.plasticBlack_frontSplitter_LR_exterior.geometry}
        material={materials.plasticblack}
        position={[2.055, 0.236, 0.024]}
      />
      <mesh
        geometry={nodes.plasticBlack_meshFront_LR_exterior.geometry}
        material={materials.plasticblack}
        position={[2.084, 0.351, 0.024]}
      />
      <mesh
        geometry={nodes.plasticBlack_sideSkirt_LR_exterior.geometry}
        material={materials.plasticblack}
        position={[-0.34, 0.231, 0.024]}
      />
      <mesh
        geometry={nodes.plasticBlack_sideWindowFrame_LR_exterior.geometry}
        material={materials.plasticblack}
        position={[-0.309, 1.031, 0.024]}
      />
      <mesh
        geometry={nodes.plasticBlack_wiperPanel_LR_exterior.geometry}
        material={materials.plasticblack}
        position={[0.772, 0.925, -0.009]}
      />
      <mesh
        geometry={nodes.plasticBlack_wipers_LR_exterior.geometry}
        material={materials.plasticblack}
        position={[0.738, 0.972, 0.11]}
      />
      <mesh
        geometry={nodes.plasticD_bumper_f001_LR_exterior.geometry}
        material={materials.plasticblackD}
        position={[1.969, 0.363, 0.024]}
      />
      <mesh
        geometry={nodes.plasticD_headlight_LR_exterior.geometry}
        material={materials.plasticblackD}
        position={[1.875, 0.684, 0.024]}
      />
      <mesh
        geometry={nodes.plasticD_underbody_LR_exterior.geometry}
        material={materials.plasticblackD}
        position={[-0.431, 0.366, 0.024]}
      />
      <mesh
        geometry={nodes.plasticGlossy_5_0_l_LR_exterior.geometry}
        material={materials.plasticGlossy}
        position={[0.79, 0.724, -0.881]}
      />
      <mesh
        geometry={nodes.plasticGlossy_5_0_r_LR_exterior.geometry}
        material={materials.plasticGlossy}
        position={[0.779, 0.724, 0.928]}
      />
      <mesh
        geometry={nodes.plasticGlossy_grille_LR_exterior.geometry}
        material={materials.plasticGlossy}
        position={[2.195, 0.588, 0.059]}
      />
      <mesh
        geometry={nodes.plasticGlossy_gt_r_LR_exterior.geometry}
        material={materials.plasticGlossy}
        position={[-2.37, 0.831, 0.015]}
      />
      <mesh
        geometry={nodes.plasticGlossy_hood_LR_exterior.geometry}
        material={materials.plasticGlossy}
        position={[1.847, 0.898, 0.024]}
      />
      <mesh
        geometry={nodes.plasticGlossy_rearSpoiler_LR_exterior.geometry}
        material={materials.plasticGlossy}
        position={[-2.286, 1.013, 0.024]}
      />
      <mesh
        geometry={nodes.plasticGlossyX_grilleMesh_LR_exterior.geometry}
        material={materials.plasticGlossyX}
        position={[2.171, 0.622, 0.024]}
      />
      <mesh
        geometry={nodes.plasticGlossyX_logo_f_LR_exterior.geometry}
        material={materials.plasticGlossyX}
        position={[2.216, 0.634, 0.019]}
      />
      <mesh
        geometry={nodes.plasticMatt_5_0_l_LR_exterior.geometry}
        material={materials.plasticMatt}
        position={[0.788, 0.725, -0.882]}
      />
      <mesh
        geometry={nodes.plasticMatt_5_0_r_LR_exterior.geometry}
        material={materials.plasticMatt}
        position={[0.781, 0.725, 0.93]}
      />
      <mesh
        geometry={nodes.plasticMatt_gt_r_LR_exterior.geometry}
        material={materials.plasticMatt}
        position={[-2.371, 0.833, 0.014]}
      />
      <mesh
        geometry={nodes.plasticRed_5_0_l_LR_exterior.geometry}
        material={materials.Red}
        position={[0.785, 0.712, -1.627]}
      />
      <mesh
        geometry={nodes.plasticRed_5_0_r_LR_exterior.geometry}
        material={materials.Red}
        position={[0.784, 0.712, 0.186]}
      />
      <mesh
        geometry={nodes.redIllum_bumper_r_LR_exterior.geometry}
        material={materials.red_illum}
        position={[-1.82, 0.417, 0.024]}
      />
      <mesh
        geometry={nodes.reflectBumpB_bumper_f_LR_exterior.geometry}
        material={materials.reflectBumpB}
        position={[1.75, 0.45, 0.024]}
      />
      <mesh
        geometry={nodes.reflectBumpB_bumper_r2_LR_exterior.geometry}
        material={materials.reflectBumpB}
        position={[-1.805, 0.463, 0.024]}
      />
      <mesh
        geometry={nodes.reflectBumpB_bumper_r_LR_exterior.geometry}
        material={materials.reflectBumpB}
        position={[-2.341, 0.415, 0.024]}
      />
      <mesh
        geometry={nodes.black_windshield001_LR_exterior.geometry}
        material={materials.black}
        position={[0.252, 1.243, -0.083]}
      />
      <mesh
        geometry={nodes.glassDark_camFront_LR_exterior.geometry}
        material={materials.glass_dark}
        position={[0.194, 1.259, 0.064]}
      />
      <mesh
        geometry={nodes.glassDark_windshield_LR_exterior.geometry}
        material={materials.glass_dark}
        position={[0.426, 1.106, 0.024]}
      />
      <mesh
        geometry={nodes.grey_camFront_LR_exterior.geometry}
        material={materials.grey}
        position={[0.196, 1.261, 0.082]}
      />
      <mesh
        geometry={nodes.plasticD_windshield001_LR_exterior.geometry}
        material={materials.plasticblackD}
        position={[0.37, 1.133, 0.029]}
      />
      <mesh
        geometry={nodes.plasticGlossy_roof_LR_exterior.geometry}
        material={materials.plasticGlossy}
        position={[-0.554, 1.327, 0.024]}
      />
      <mesh
        geometry={nodes.white_windshieldLogo_LR_exterior.geometry}
        material={materials.white}
        position={[0.166, 1.282, 0.004]}
      />
      <mesh
        geometry={nodes.chromeDark_headlight_LR_exterior.geometry}
        material={materials.chromeDark}
        position={[1.945, 0.686, 0.024]}
      />
      <mesh
        geometry={nodes.chromeMatt_headlights_LR_exterior.geometry}
        material={materials.chromeMatt}
        position={[1.919, 0.689, 0.024]}
      />
      <mesh
        geometry={nodes.glassBumpA_reverse_light_LR_exterior.geometry}
        material={materials.glass_bumpA}
        position={[-2.458, 0.348, 0.024]}
      />
      <mesh
        geometry={nodes.glassClear_brakeLight_LR_exterior.geometry}
        material={materials.glass_clear}
        position={[-1.038, 1.291, 0.024]}
      />
      <mesh
        geometry={nodes.glassClear_headlights_LR_exterior.geometry}
        material={materials.glass_clear}
        position={[1.937, 0.697, 0.024]}
      />
      <mesh
        geometry={nodes.reflect_brakeLight001_LR_exterior.geometry}
        material={materials.reflect}
        position={[-1.031, 1.292, 0.024]}
      />
      <mesh
        geometry={nodes.reflect_headlight_beams_LR_exterior.geometry}
        material={materials.reflect}
        position={[1.903, 0.688, 0.024]}
      />
      <mesh
        geometry={nodes.reflect_headlights_top_LR_exterior.geometry}
        material={materials.reflect}
        position={[1.95, 0.72, 0.024]}
      />
      <mesh
        geometry={nodes.reflect_reverseLight_MSx1_LR_exterior.geometry}
        material={materials["reflect.001"]}
        position={[-2.424, 0.347, 0.024]}
      />
      <mesh
        geometry={nodes.reflect_taillights001_LR_exterior.geometry}
        material={materials.reflect}
        position={[-2.233, 0.848, 0.024]}
      />
      <mesh
        geometry={
          nodes.plasticGlossy_headlightDetails_MSx1_LR_exterior.geometry
        }
        material={materials.plasticGlossy}
        position={[1.766, 0.698, 0.024]}
      />
      <mesh
        geometry={nodes.plasticGlossy_headlights_LR_exterior.geometry}
        material={materials.plasticGlossy}
        position={[1.918, 0.706, 0.162]}
      />
      <mesh
        geometry={nodes.plasticGlossy_taillights_LR_exterior.geometry}
        material={materials.plasticGlossy}
        position={[-2.275, 0.844, 0.024]}
      />
      <mesh
        geometry={nodes.plasticGlossyBumpA_headlight_LR_exterior.geometry}
        material={materials.plasticGlossy_bumpA}
        position={[2.075, 0.672, 0.024]}
      />
    </group>
  );
}

useGLTF.preload("./model/FordMustangGT_2023.gltf");

export default FordMustangGT_2023;
